/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestFrame.java
 *
 * Created on 06.08.2011, 11:45:47
 */
package org.ubs.scanner;

import gnu.io.NoSuchPortException;
import gnu.io.PortInUseException;
import gnu.io.UnsupportedCommOperationException;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.TooManyListenersException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author developer
 */
public class TestFrame extends javax.swing.JFrame {
    
    BarcodeScanner scanner;

    /** Creates new form TestFrame */
    public TestFrame() {
        initComponents();
        Path pathToSystemXML = Paths.get(System.getProperty("user.home"),
                ".saas", "app", "config", "system.xml");
        scanner = BarcodeScannerFactory.getBarcodeScanner(pathToSystemXML);
        scanner.addScannerEventListener(new ScannerEventListener() {
            
            @Override
            public void catchCode(ScannerEvent evt) {
                lblCode.setText("" + evt.getCode());
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCode = new javax.swing.JLabel();
        btnEnable = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCode.setText("jLabel1");

        btnEnable.setText("Enable");
        btnEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(btnEnable, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(btnEnable)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableActionPerformed
        try {
            // TODO add your handling code here:
            scanner.setEnable(btnEnable.isSelected());
        } catch (NoSuchPortException | PortInUseException | UnsupportedCommOperationException | TooManyListenersException | IOException ex) {
            Logger.getGlobal().log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String osName = System.getProperty("os.name");
        String osArch = System.getProperty("os.arch");
        System.out.println("os name = " + osName);
        System.out.println("os architecture = " + osArch);

        if (osName.indexOf("Windows") != -1) {
            osName = "Windows";
        }

        try {
            Path cashMachineLibPath = Paths.get(System.getProperty("user.home"),
                    ".saas", "app", "rxtx", osName, osArch);
            Path videoLibPath = Paths.get(System.getProperty("user.home"),
                    ".saas", "app", "video");
            String newPath = cashMachineLibPath.toString() + File.pathSeparator + videoLibPath;
            System.setProperty("java.library.path", newPath);
            Field fieldSysPath = ClassLoader.class.getDeclaredField("sys_paths");
            fieldSysPath.setAccessible(true);
            if (fieldSysPath != null) {
                fieldSysPath.set(System.class.getClassLoader(), null);
            }
        } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
            Logger.getGlobal().log(Level.WARNING, osArch, e);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEnable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCode;
    // End of variables declaration//GEN-END:variables
}
