
package examples;

import java.nio.file.Path;
import java.nio.file.Paths;
import db.*;
import java.util.ArrayList;
import org.uui.db.DataBase;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

public class CatalogEditor extends javax.swing.JFrame {
    private DataBase db;
    private Matherials matherial = null;
    private DocumentsTb doc = null;
    private Stanki stan = null;
    private Suppliers supp = null;
    
    /**
     * Creates new form CatalogEditor
     */
    public CatalogEditor() {
        Path p = Paths.get(System.getProperty("user.dir"), "db.properties");
        db = DataBase.getInstance(p.toString());
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        list1 = new java.awt.List();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogs");
        setName("Form");
        setPreferredSize(new java.awt.Dimension(667, 468));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" Name "));
        jPanel1.setName("");
        jPanel1.setPreferredSize(new java.awt.Dimension(496, 80));
        jPanel1.setRequestFocusEnabled(false);

        jLabel1.setText("Наименование:");
        jLabel1.setName("jLabel1");

        jTextField1.setName("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Пример: Сталь 12Х2Н4А-Ш ГОСТ4543-71");
        jLabel4.setName("jLabel4");

        jTextField2.setName("jTextField2");

        jLabel3.setText("jLabel3");
        jLabel3.setName("jLabel3");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField1)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jTextField2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(" E-mail "));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setName("");

        jButton1.setText("Add");
        jButton1.setName("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove");
        jButton3.setName("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        list1.setName("list1");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(list1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton3))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {jButton1, jButton3}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton3)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, list1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        jButton5.setText("Cancel");
        jButton5.setName("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("OK");
        jButton6.setName("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Каталог материалов", "Документы по ТБ", "Станки", "Поставщики материалов" }));
        jComboBox1.setSelectedItem(this);
        jComboBox1.setName("jComboBox1");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(0, 525, Short.MAX_VALUE)
                                .add(jButton6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton5))
                            .add(jPanel1, 0, 643, Short.MAX_VALUE)
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 271, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(new java.awt.Component[] {jButton5, jButton6}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton5)
                    .add(jButton6)))
        );

        jPanel1.getAccessibleContext().setAccessibleName("\"Name\"");
        jPanel2.getAccessibleContext().setAccessibleName("bd");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().isEmpty()!=true){
        switch (jComboBox1.getSelectedIndex())
        {
            case 0:
            {
                 matherial = new Matherials();
        matherial.setName(jTextField1.getText());
        long id = db.addObject(matherial);
        list1.add(id+":"+jTextField1.getText());  
                break;
            }
                case 1:
            {
                doc = new DocumentsTb();
        doc.setName(jTextField1.getText());
        long id = db.addObject(doc);
        list1.add(id+":"+jTextField1.getText());        
                break;
            }
            case 2:
            {
                 stan = new Stanki();
        stan.setNumber(jTextField1.getText());
        long id = db.addObject(stan);
        list1.add(id+":"+jTextField1.getText());     
                break;
            }
                case 3:
            {
                supp = new Suppliers();
        supp.setName(jTextField1.getText());
        supp.setTel(jTextField2.getText());
        long id = db.addObject(supp);
        list1.add(id+":"+jTextField1.getText()+";"+jTextField2.getText()); 
                break;
            }
        }
        
        } else {  JFrame f = new JFrame();JOptionPane.showMessageDialog(f,"Не введено название");}
        
       // list1.gets
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (list1.getSelectedIndex()!=-1){
        switch (jComboBox1.getSelectedIndex())
        {
         
                   
         
            case 0:
            {
             db.deleteObject(Matherials.class.getName(),Long.valueOf(list1.getSelectedItem().substring(0, 2)));
        list1.remove(list1.getSelectedIndex()); 
                break;
            }
                case 1:
            {
                  db.deleteObject(DocumentsTb.class.getName(),Long.valueOf(list1.getSelectedItem().substring(0, 2)));
        list1.remove(list1.getSelectedIndex());      
                break;
            }
            case 2:
            {
                 db.deleteObject(Stanki.class.getName(),Long.valueOf(list1.getSelectedItem().substring(0, 2)));
        list1.remove(list1.getSelectedIndex());     
                break;
            }
                case 3:
            {
                db.deleteObject(Suppliers.class.getName(),Long.valueOf(list1.getSelectedItem().substring(0, 2)));
        list1.remove(list1.getSelectedIndex()); 
                break;
            }
        }
     
        } else {  JFrame f = new JFrame();JOptionPane.showMessageDialog(f,"Не выбран элемент для удаления");}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //jComboBox1.getSelectedItem().toString());
        list1.removeAll();
        switch (jComboBox1.getSelectedIndex())
        {
            case 0:
            {
                ArrayList<Matherials> matlist = db.getAllObjectsList(Matherials.class.getName());
      
        for (Matherials mat : matlist) 
        {
            list1.add(mat.getId()+":"+mat.getName());
        }
   jLabel4.setText("Пример: Сталь 12Х2Н4А-Ш ГОСТ4543-71");
               jLabel3.setVisible(false);
        jTextField2.setVisible(false);      
                break;
            }
                case 1:
            {
                ArrayList<DocumentsTb> matlist = db.getAllObjectsList(DocumentsTb.class.getName());
      
        for (DocumentsTb dt : matlist) 
        {
            list1.add(dt.getId()+":"+dt.getName());
        }
                jLabel4.setText("Пример: ИТБ 12.03.001-86");
                   jLabel3.setVisible(false);
        jTextField2.setVisible(false);      
                break;
            }
            case 2:
            {
                ArrayList<Stanki> matlist = db.getAllObjectsList(Stanki.class.getName());
      
        for (Stanki st : matlist) 
        {
            list1.add(st.getId()+":"+st.getNumber());
        }
                  jLabel3.setVisible(false);
        jTextField2.setVisible(false);
                jLabel1.setText("Номер:");
                jLabel4.setText("Пример: ГКМ ВБ1139");        
                break;
            }
                case 3:
            {
                ArrayList<Suppliers> matlist = db.getAllObjectsList(Suppliers.class.getName());
      
        for (Suppliers sp : matlist) 
        {
            list1.add(sp.getId()+":"+sp.getName()+";"+sp.getTel());
        }
                jLabel1.setText("Наименование:");
                jLabel4.setText("Пример: ООО Рога и копыта");
                jLabel3.setVisible(true);
        jTextField2.setVisible(true);
        jLabel3.setText("Телефон:");
                break;
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Catalog"));
        jLabel3.setVisible(false);
        jTextField2.setVisible(false);
       // jLabel2.setText(String.valueOf(jComboBox1.getSelectedIndex()));
        ArrayList<Matherials> matlist = db.getAllObjectsList(Matherials.class.getName());
      
        for (Matherials mat : matlist) 
        {
            list1.add(mat.getId()+":"+mat.getName());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogEditor().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
    
}
